# Generated by Django 6.0.3 on 2026-03-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0008_bill_bill_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="bill_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="rating",
            name="r_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
